#!/bin/bash -e

FILES="slides.js generate.js template.html"

(cd reveal.js && node_modules/.bin/grunt serve) &

node_modules/.bin/onchange $FILES -- bash -c '\
  echo "Reload $(date)" && \
  npm run-script -s generate | sponge reveal.js/index.html \
'
